# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_Name', models.CharField(max_length=80)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=200)),
                ('Date_Time', models.DateTimeField()),
                ('Contact', models.TextField(max_length=150)),
                ('Obj_Name', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
