# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20160917_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
