# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20160917_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Date_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
