# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20160917_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Obj_Name',
            new_name='Item_Name',
        ),
    ]
